name = "sefbot-path"
main = "src/index.js"
compatibility_date = "2026-07-01"
account_id = "114651c9288b7d9012b396fe66737d16"

routes = [
  { pattern = "wearegays.net/sefbot*", zone_name = "wearegays.net" },
  { pattern = "www.wearegays.net/sefbot*", zone_name = "wearegays.net" },
  { pattern = "wearegays.net/healthz", zone_name = "wearegays.net" },
  { pattern = "www.wearegays.net/healthz", zone_name = "wearegays.net" },
  { pattern = "wearegays.net/readyz", zone_name = "wearegays.net" },
  { pattern = "www.wearegays.net/readyz", zone_name = "wearegays.net" },
]

[vars]
SEFBOT_ORIGIN = "http://paid5.daki.cc:4204"
