#!/usr/bin/env python3
"""Generate or verify the public slash-command catalog from registration code."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ.setdefault("DISCORD_TOKEN", "documentation-token")
os.environ.setdefault("OWAUA_LOAD_DOTENV", "0")

import discord  # noqa: E402
from discord import app_commands  # noqa: E402

from owaua import slash  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "SLASH_COMMANDS.md"


def _clean(value: object) -> str:
    return " ".join(str(value or "").replace("|", r"\|").split())


def render() -> str:
    client = discord.Client(intents=discord.Intents.none())
    tree = slash.setup(client, lambda *_args: None)
    commands = sorted(tree.get_commands(), key=lambda command: command.name)
    rows: list[tuple[str, str, str]] = []
    for command in commands:
        if isinstance(command, app_commands.Group):
            for child in sorted(command.commands, key=lambda item: item.name):
                rows.append(
                    (
                        f"/{command.name} {child.name}",
                        "slash",
                        _clean(getattr(child, "description", "")),
                    )
                )
            continue
        command_type = "message menu" if isinstance(command, app_commands.ContextMenu) else "slash"
        rows.append(
            (
                command.name if command_type == "message menu" else f"/{command.name}",
                command_type,
                _clean(getattr(command, "description", "")) or "Context action.",
            )
        )
    lines = [
        "# owaua Discord application commands",
        "",
        "Generated by `scripts/generate_slash_reference.py`; do not edit by hand.",
        "",
        f"Top-level Discord command count: **{len(commands)}** (limit: 100).",
        "",
        "| Command | Type | Description |",
        "| --- | --- | --- |",
    ]
    lines.extend(f"| `{name}` | {kind} | {description} |" for name, kind, description in rows)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if SLASH_COMMANDS.md drifted")
    args = parser.parse_args()
    rendered = render()
    if not args.check:
        sys.stdout.write(rendered)
        return 0
    current = REFERENCE.read_text(encoding="utf-8") if REFERENCE.exists() else ""
    if current == rendered:
        print(f"{REFERENCE.name} is current")
        return 0
    print(
        f"{REFERENCE.name} is stale; regenerate with "
        "`OWAUA_LOAD_DOTENV=0 PYTHONPATH=src python scripts/generate_slash_reference.py`",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
